# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.Account do
  @moduledoc """
  Represents high level account info. Used when returning entire account information would not be useful like the getAllAccounts operation
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :account_number,
    :status,
    :crypto_status,
    :currency,
    :created_at,
    :last_equity,
    :kyc_results,
    :account_type
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :account_number => String.t | nil,
    :status => BrokerAPI.Model.AccountStatus.t,
    :crypto_status => BrokerAPI.Model.AccountStatus.t | nil,
    :currency => String.t,
    :created_at => DateTime.t,
    :last_equity => String.t,
    :kyc_results => BrokerAPI.Model.KycResult.t | nil,
    :account_type => BrokerAPI.Model.AccountType.t | nil
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:status, :struct, BrokerAPI.Model.AccountStatus)
     |> Deserializer.deserialize(:crypto_status, :struct, BrokerAPI.Model.AccountStatus)
     |> Deserializer.deserialize(:created_at, :datetime, nil)
     |> Deserializer.deserialize(:kyc_results, :struct, BrokerAPI.Model.KycResult)
     |> Deserializer.deserialize(:account_type, :struct, BrokerAPI.Model.AccountType)
  end
end

