# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.AccountUpdateRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :contact,
    :identity,
    :disclosures,
    :trustedContact
  ]

  @type t :: %__MODULE__{
    :contact => BrokerAPI.Model.Contact.t | nil,
    :identity => BrokerAPI.Model.Identity.t | nil,
    :disclosures => BrokerAPI.Model.Disclosures.t | nil,
    :trustedContact => BrokerAPI.Model.TrustedContact.t | nil
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:contact, :struct, BrokerAPI.Model.Contact)
     |> Deserializer.deserialize(:identity, :struct, BrokerAPI.Model.Identity)
     |> Deserializer.deserialize(:disclosures, :struct, BrokerAPI.Model.Disclosures)
     |> Deserializer.deserialize(:trustedContact, :struct, BrokerAPI.Model.TrustedContact)
  end
end

