# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.AccountCreationRequest do
  @moduledoc """
  Represents the fields required to create a new account
  """

  @derive Jason.Encoder
  defstruct [
    :contact,
    :identity,
    :disclosures,
    :agreements,
    :documents,
    :trusted_contact
  ]

  @type t :: %__MODULE__{
    :contact => BrokerAPI.Model.Contact.t,
    :identity => BrokerAPI.Model.Identity.t,
    :disclosures => BrokerAPI.Model.Disclosures.t,
    :agreements => [BrokerAPI.Model.Agreement.t],
    :documents => [BrokerAPI.Model.DocumentUploadRequest.t] | nil,
    :trusted_contact => BrokerAPI.Model.TrustedContact.t | nil
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:contact, :struct, BrokerAPI.Model.Contact)
     |> Deserializer.deserialize(:identity, :struct, BrokerAPI.Model.Identity)
     |> Deserializer.deserialize(:disclosures, :struct, BrokerAPI.Model.Disclosures)
     |> Deserializer.deserialize(:agreements, :list, BrokerAPI.Model.Agreement)
     |> Deserializer.deserialize(:documents, :list, BrokerAPI.Model.DocumentUploadRequest)
     |> Deserializer.deserialize(:trusted_contact, :struct, BrokerAPI.Model.TrustedContact)
  end
end

