# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.AchRelationship do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :created_at,
    :updated_at,
    :account_id,
    :status,
    :account_owner_name,
    :bank_account_type,
    :bank_account_number,
    :bank_routing_number,
    :nickname
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :created_at => DateTime.t,
    :updated_at => DateTime.t,
    :account_id => String.t,
    :status => String.t,
    :account_owner_name => String.t,
    :bank_account_type => String.t | nil,
    :bank_account_number => String.t | nil,
    :bank_routing_number => String.t | nil,
    :nickname => String.t | nil
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_at, :datetime, nil)
     |> Deserializer.deserialize(:updated_at, :datetime, nil)
  end
end

