# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.ActivityType do
  @moduledoc """
  Represents the various kinds of activity.  TradeActivity's will always have the type `FILL`  - **FILL**   Order Fills (Partial/Full) - **ACATC**   ACATS IN/OUT (Cash) - **ACATS**   ACATS IN/OUT (Securities) - **CIL**   Cash in Lieu of Stock - **CSD**   Cash Disbursement (+) - **CSW**   Cash Withdrawable - **DIV**   Dividend - **DIVCGL**   Dividend (Capital Gain Long Term) - **DIVCGS**   Dividend (Capital Gain Short Term) - **DIVNRA**   Dividend Adjusted (NRA Withheld) - **DIVROC**   Dividend Return of Capital - **DIVTXEX**   Dividend (Tax Exempt) - **FEE**   REG and TAF Fees - **INT**   Interest (Credit/Margin) - **JNLC**   Journal Entry (Cash) - **JNLS**   Journal Entry (Stock) - **MA**   Merger/Acquisition - **PTC**   Pass Thru Change - **REORG**   Reorg CA - **SPIN**   Stock Spinoff - **SPLIT**   Stock Split
  """

  @derive Jason.Encoder
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }

  def decode(value) do
    value
  end
end

