# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.ApplicationDocument do
  @moduledoc """
  If an account has documents on the application submission, it has the ApplicationDocument model in exchange with DocumentUpload. 
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :document_type,
    :document_sub_type,
    :mime_type,
    :created_at
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :document_type => BrokerAPI.Model.DocumentType.t,
    :document_sub_type => String.t | nil,
    :mime_type => String.t | nil,
    :created_at => DateTime.t
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:document_type, :struct, BrokerAPI.Model.DocumentType)
     |> Deserializer.deserialize(:created_at, :datetime, nil)
  end
end

