# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.AuthorizeOAuthTokenResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :code,
    :client_id,
    :redirect_uri,
    :scope
  ]

  @type t :: %__MODULE__{
    :code => String.t,
    :client_id => String.t,
    :redirect_uri => String.t,
    :scope => String.t
  }

  def decode(value) do
    value
  end
end

