# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.Bank do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :created_at,
    :updated_at,
    :account_id,
    :status,
    :name,
    :bank_code,
    :bank_code_type,
    :country,
    :state_province,
    :postal_code,
    :city,
    :street_address,
    :account_number
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :created_at => DateTime.t,
    :updated_at => DateTime.t,
    :account_id => String.t | nil,
    :status => String.t | nil,
    :name => String.t,
    :bank_code => String.t,
    :bank_code_type => String.t,
    :country => String.t | nil,
    :state_province => String.t | nil,
    :postal_code => String.t | nil,
    :city => String.t | nil,
    :street_address => String.t | nil,
    :account_number => String.t
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_at, :datetime, nil)
     |> Deserializer.deserialize(:updated_at, :datetime, nil)
  end
end

