# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.BatchJournalRequestEntriesInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :to_account,
    :amount
  ]

  @type t :: %__MODULE__{
    :to_account => String.t,
    :amount => String.t
  }

  def decode(value) do
    value
  end
end

