# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.Calendar do
  @moduledoc """
  The calendar API serves the full list of market days from 1970 to 2029. It can also be queried by specifying a start and/or end time to narrow down the results. In addition to the dates, the response also contains the specific open and close times for the market days, taking into account early closures.
  """

  @derive Jason.Encoder
  defstruct [
    :date,
    :open,
    :close,
    :session_open,
    :session_close
  ]

  @type t :: %__MODULE__{
    :date => Date.t,
    :open => String.t,
    :close => String.t,
    :session_open => String.t | nil,
    :session_close => String.t | nil
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:date, :date, nil)
  end
end

