# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.Clock do
  @moduledoc """
  Represents the current market time and open/close events.
  """

  @derive Jason.Encoder
  defstruct [
    :timestamp,
    :is_open,
    :next_open,
    :next_close
  ]

  @type t :: %__MODULE__{
    :timestamp => DateTime.t,
    :is_open => boolean(),
    :next_open => DateTime.t,
    :next_close => DateTime.t
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:timestamp, :datetime, nil)
     |> Deserializer.deserialize(:next_open, :datetime, nil)
     |> Deserializer.deserialize(:next_close, :datetime, nil)
  end
end

