# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.CreateWatchlistRequest do
  @moduledoc """
  This model represents the fields you can specify when Creating or Updating/Replacing a Watchlist
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :symbols
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :symbols => [String.t]
  }

  def decode(value) do
    value
  end
end

