# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.CreateBankRequest do
  @moduledoc """
  Represents the possible fields to send when creating a new associated Bank resource for an account
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :bank_code,
    :bank_code_type,
    :country,
    :state_province,
    :postal_code,
    :city,
    :street_address,
    :account_number
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :bank_code => String.t,
    :bank_code_type => String.t,
    :country => String.t | nil,
    :state_province => String.t | nil,
    :postal_code => String.t | nil,
    :city => String.t | nil,
    :street_address => String.t | nil,
    :account_number => String.t
  }

  def decode(value) do
    value
  end
end

