# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.CreateOrderRequestStopLoss do
  @moduledoc """
  Takes in a string/number values for stop_price and limit_price
  """

  @derive Jason.Encoder
  defstruct [
    :stop_price,
    :limit_price
  ]

  @type t :: %__MODULE__{
    :stop_price => String.t | nil,
    :limit_price => String.t | nil
  }

  def decode(value) do
    value
  end
end

