# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.CreateTransferRequest do
  @moduledoc """
  [See main docs here](https://alpaca.markets/docs/api-references/broker-api/funding/transfers/#creating-a-transfer-entity)
  """

  @derive Jason.Encoder
  defstruct [
    :transfer_type,
    :relationship_id,
    :bank_id,
    :amount,
    :direction,
    :timing,
    :additional_information
  ]

  @type t :: %__MODULE__{
    :transfer_type => BrokerAPI.Model.TransferType.t,
    :relationship_id => String.t | nil,
    :bank_id => String.t | nil,
    :amount => String.t,
    :direction => BrokerAPI.Model.TransferDirection.t,
    :timing => BrokerAPI.Model.TransferTiming.t,
    :additional_information => String.t | nil
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:transfer_type, :struct, BrokerAPI.Model.TransferType)
     |> Deserializer.deserialize(:direction, :struct, BrokerAPI.Model.TransferDirection)
     |> Deserializer.deserialize(:timing, :struct, BrokerAPI.Model.TransferTiming)
  end
end

