# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.CustodialAccountMinorIdentity do
  @moduledoc """
  Represents Identity information for a minor that an account of type \"custodial\" is for
  """

  @derive Jason.Encoder
  defstruct [
    :given_name,
    :family_name,
    :date_of_birth,
    :tax_id,
    :tax_id_type,
    :country_of_citizenship,
    :country_of_birth,
    :country_of_tax_residence,
    :state,
    :email
  ]

  @type t :: %__MODULE__{
    :given_name => String.t,
    :family_name => String.t,
    :date_of_birth => Date.t,
    :tax_id => String.t | nil,
    :tax_id_type => BrokerAPI.Model.TaxIdType.t | nil,
    :country_of_citizenship => String.t | nil,
    :country_of_birth => String.t | nil,
    :country_of_tax_residence => String.t,
    :state => String.t,
    :email => String.t
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:date_of_birth, :date, nil)
     |> Deserializer.deserialize(:tax_id_type, :struct, BrokerAPI.Model.TaxIdType)
  end
end

