# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.DisclosureContextAnnotation do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :context_type,
    :company_name,
    :company_street_address,
    :company_city,
    :company_state,
    :company_country,
    :company_compliance_email,
    :given_name,
    :family_name
  ]

  @type t :: %__MODULE__{
    :context_type => String.t,
    :company_name => String.t | nil,
    :company_street_address => String.t | nil,
    :company_city => String.t | nil,
    :company_state => String.t | nil,
    :company_country => String.t | nil,
    :company_compliance_email => String.t | nil,
    :given_name => String.t | nil,
    :family_name => String.t | nil
  }

  def decode(value) do
    value
  end
end

