# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.Disclosures do
  @moduledoc """
  Disclosures fields denote if the account owner falls under each category defined by FINRA rule. The client has to ask questions for the end user and the values should reflect their answers. If one of the answers is true (yes), the account goes into ACTION_REQUIRED status. 
  """

  @derive Jason.Encoder
  defstruct [
    :employment_status,
    :employer_name,
    :employer_address,
    :employment_position,
    :is_control_person,
    :is_affiliated_exchange_or_finra,
    :is_politically_exposed,
    :immediate_family_exposed,
    :context
  ]

  @type t :: %__MODULE__{
    :employment_status => String.t | nil,
    :employer_name => String.t | nil,
    :employer_address => String.t | nil,
    :employment_position => String.t | nil,
    :is_control_person => boolean(),
    :is_affiliated_exchange_or_finra => boolean(),
    :is_politically_exposed => boolean(),
    :immediate_family_exposed => boolean(),
    :context => [BrokerAPI.Model.DisclosureContextAnnotation.t] | nil
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:context, :list, BrokerAPI.Model.DisclosureContextAnnotation)
  end
end

