# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.DocumentType do
  @moduledoc """
  - identity_verification:   identity verification document  - address_verification:   address verification document  - date_of_birth_verification:   date of birth verification document  - tax_id_verification:   tax ID verification document  - account_approval_letter:   407 approval letter  - cip_result:   initial CIP result 
  """

  @derive Jason.Encoder
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }

  def decode(value) do
    value
  end
end

