# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.Error do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :code,
    :message
  ]

  @type t :: %__MODULE__{
    :code => float(),
    :message => String.t
  }

  def decode(value) do
    value
  end
end

