# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.Exchange do
  @moduledoc """
  Represents the exchange where an asset is traded.  For Stocks: - AMEX - ARCA - BATS - NYSE - NASDAQ - NYSEARCA - OTC  For Crypto: - ERSX - FTXU
  """

  @derive Jason.Encoder
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }

  def decode(value) do
    value
  end
end

