# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.Identity do
  @moduledoc """
  Identity is the model to provide account owner’s identity information. 
  """

  @derive Jason.Encoder
  defstruct [
    :given_name,
    :family_name,
    :date_of_birth,
    :tax_id,
    :tax_id_type,
    :country_of_citizenship,
    :country_of_birth,
    :country_of_tax_residence,
    :funding_source,
    :annual_income_min,
    :annual_income_max,
    :liquid_net_worth_min,
    :liquid_net_worth_max,
    :total_net_worth_min,
    :total_net_worth_max,
    :extra
  ]

  @type t :: %__MODULE__{
    :given_name => String.t,
    :family_name => String.t,
    :date_of_birth => Date.t,
    :tax_id => String.t | nil,
    :tax_id_type => BrokerAPI.Model.TaxIdType.t | nil,
    :country_of_citizenship => String.t | nil,
    :country_of_birth => String.t | nil,
    :country_of_tax_residence => String.t,
    :funding_source => [String.t],
    :annual_income_min => float() | nil,
    :annual_income_max => float() | nil,
    :liquid_net_worth_min => float() | nil,
    :liquid_net_worth_max => float() | nil,
    :total_net_worth_min => float() | nil,
    :total_net_worth_max => float() | nil,
    :extra => map() | nil
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:date_of_birth, :date, nil)
     |> Deserializer.deserialize(:tax_id_type, :struct, BrokerAPI.Model.TaxIdType)
  end
end

