# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.IssueOAuthTokenResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :access_token,
    :token_type,
    :scope
  ]

  @type t :: %__MODULE__{
    :access_token => String.t,
    :token_type => String.t,
    :scope => String.t
  }

  def decode(value) do
    value
  end
end

