# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.Jnlc do
  @moduledoc """
  Journal information specific to cash transfers. This field is required for `Journal`s with an `entry_type` of `jnlc` (cash transfers), but will be null for those with `jnls` (securities transfers).
  """

  @derive Jason.Encoder
  defstruct [
    :description,
    :net_amount,
    :transmitter_name,
    :transmitter_account_number,
    :transmitter_address,
    :transmitter_financial_institution,
    :transmitter_timestamp
  ]

  @type t :: %__MODULE__{
    :description => String.t | nil,
    :net_amount => String.t,
    :transmitter_name => String.t | nil,
    :transmitter_account_number => String.t | nil,
    :transmitter_address => String.t | nil,
    :transmitter_financial_institution => String.t | nil,
    :transmitter_timestamp => DateTime.t | nil
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:transmitter_timestamp, :datetime, nil)
  end
end

