# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.Jnls do
  @moduledoc """
  Journal information specific to securities transfers. This field is required for `Journal`s with an `entry_type` of `jnls` (securities transfers), but will be null for those with `jnlc` (cash transfers).
  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :qty,
    :price
  ]

  @type t :: %__MODULE__{
    :symbol => String.t,
    :qty => String.t,
    :price => String.t
  }

  def decode(value) do
    value
  end
end

