# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.JournalEntryType do
  @moduledoc """
  This enum represents the various kinds of Journal alpaca supports.  Current values are:  - **JNLC**    Journal Cash between accounts  - **JNLS**    Journal Securities between accounts
  """

  @derive Jason.Encoder
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }

  def decode(value) do
    value
  end
end

