# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.JournalResource do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :description,
    :net_amount,
    :transmitter_name,
    :transmitter_account_number,
    :transmitter_address,
    :transmitter_financial_institution,
    :transmitter_timestamp,
    :symbol,
    :qty,
    :price
  ]

  @type t :: %__MODULE__{
    :description => String.t | nil,
    :net_amount => String.t,
    :transmitter_name => String.t | nil,
    :transmitter_account_number => String.t | nil,
    :transmitter_address => String.t | nil,
    :transmitter_financial_institution => String.t | nil,
    :transmitter_timestamp => DateTime.t | nil,
    :symbol => String.t,
    :qty => String.t,
    :price => String.t
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:transmitter_timestamp, :datetime, nil)
  end
end

