# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.JournalData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :entry_type,
    :from_account,
    :to_account,
    :amount,
    :symbol,
    :qty
  ]

  @type t :: %__MODULE__{
    :entry_type => BrokerAPI.Model.JournalEntryType.t,
    :from_account => String.t,
    :to_account => String.t,
    :amount => String.t | nil,
    :symbol => String.t | nil,
    :qty => String.t | nil
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:entry_type, :struct, BrokerAPI.Model.JournalEntryType)
  end
end

