# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.OAuthTokenRequest do
  @moduledoc """
  This model is used for both the Issue and Authorize OAuth token routes
  """

  @derive Jason.Encoder
  defstruct [
    :client_id,
    :client_secret,
    :redirect_uri,
    :scope,
    :account_id
  ]

  @type t :: %__MODULE__{
    :client_id => String.t,
    :client_secret => String.t,
    :redirect_uri => String.t,
    :scope => String.t,
    :account_id => String.t
  }

  def decode(value) do
    value
  end
end

