# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.OathClientResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :client_id,
    :name,
    :description,
    :url,
    :terms_of_use,
    :privacy_policy,
    :status,
    :redirect_uri,
    :live_trading_approved
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :name => String.t | nil,
    :description => String.t | nil,
    :url => String.t | nil,
    :terms_of_use => String.t | nil,
    :privacy_policy => String.t | nil,
    :status => String.t | nil,
    :redirect_uri => [String.t] | nil,
    :live_trading_approved => boolean() | nil
  }

  def decode(value) do
    value
  end
end

