# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.Order do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :client_order_id,
    :created_at,
    :updated_at,
    :submitted_at,
    :filled_at,
    :expired_at,
    :canceled_at,
    :failed_at,
    :replaced_at,
    :replaced_by,
    :replaces,
    :asset_id,
    :symbol,
    :asset_class,
    :notional,
    :qty,
    :filled_qty,
    :filled_avg_price,
    :order_class,
    :order_type,
    :type,
    :side,
    :time_in_force,
    :limit_price,
    :stop_price,
    :status,
    :extended_hours,
    :legs,
    :trail_price,
    :trail_percent,
    :hwm,
    :commission
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :client_order_id => String.t | nil,
    :created_at => DateTime.t | nil,
    :updated_at => DateTime.t | nil,
    :submitted_at => DateTime.t | nil,
    :filled_at => DateTime.t | nil,
    :expired_at => DateTime.t | nil,
    :canceled_at => DateTime.t | nil,
    :failed_at => DateTime.t | nil,
    :replaced_at => DateTime.t | nil,
    :replaced_by => String.t | nil,
    :replaces => String.t | nil,
    :asset_id => String.t | nil,
    :symbol => String.t,
    :asset_class => BrokerAPI.Model.AssetClass.t | nil,
    :notional => String.t | nil,
    :qty => String.t | nil,
    :filled_qty => String.t | nil,
    :filled_avg_price => String.t | nil,
    :order_class => BrokerAPI.Model.OrderClass.t | nil,
    :order_type => BrokerAPI.Model.OrderType.t | nil,
    :type => BrokerAPI.Model.OrderType.t | nil,
    :side => BrokerAPI.Model.OrderSide.t | nil,
    :time_in_force => BrokerAPI.Model.TimeInForce.t | nil,
    :limit_price => String.t | nil,
    :stop_price => String.t | nil,
    :status => BrokerAPI.Model.OrderStatus.t | nil,
    :extended_hours => boolean() | nil,
    :legs => [BrokerAPI.Model.Order.t] | nil,
    :trail_price => String.t | nil,
    :trail_percent => String.t | nil,
    :hwm => String.t | nil,
    :commission => String.t | nil
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_at, :datetime, nil)
     |> Deserializer.deserialize(:updated_at, :datetime, nil)
     |> Deserializer.deserialize(:submitted_at, :datetime, nil)
     |> Deserializer.deserialize(:filled_at, :datetime, nil)
     |> Deserializer.deserialize(:expired_at, :datetime, nil)
     |> Deserializer.deserialize(:canceled_at, :datetime, nil)
     |> Deserializer.deserialize(:failed_at, :datetime, nil)
     |> Deserializer.deserialize(:replaced_at, :datetime, nil)
     |> Deserializer.deserialize(:asset_class, :struct, BrokerAPI.Model.AssetClass)
     |> Deserializer.deserialize(:order_class, :struct, BrokerAPI.Model.OrderClass)
     |> Deserializer.deserialize(:order_type, :struct, BrokerAPI.Model.OrderType)
     |> Deserializer.deserialize(:type, :struct, BrokerAPI.Model.OrderType)
     |> Deserializer.deserialize(:side, :struct, BrokerAPI.Model.OrderSide)
     |> Deserializer.deserialize(:time_in_force, :struct, BrokerAPI.Model.TimeInForce)
     |> Deserializer.deserialize(:status, :struct, BrokerAPI.Model.OrderStatus)
     |> Deserializer.deserialize(:legs, :list, BrokerAPI.Model.Order)
  end
end

