# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.PortfolioHistory do
  @moduledoc """
  Timeseries data for equity and profit loss information of the account.
  """

  @derive Jason.Encoder
  defstruct [
    :timestamp,
    :equity,
    :profit_loss,
    :profit_loss_pct,
    :base_value,
    :timeframe
  ]

  @type t :: %__MODULE__{
    :timestamp => [integer()],
    :equity => [float()],
    :profit_loss => [float()],
    :profit_loss_pct => [float()],
    :base_value => float() | nil,
    :timeframe => String.t | nil
  }

  def decode(value) do
    value
  end
end

