# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.Position do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :asset_id,
    :symbol,
    :exchange,
    :asset_class,
    :asset_marginable,
    :avg_entry_price,
    :qty,
    :side,
    :market_value,
    :cost_basis,
    :unrealized_pl,
    :unrealized_plpc,
    :unrealized_intraday_pl,
    :unrealized_intraday_plpc,
    :current_price,
    :lastday_price,
    :change_today
  ]

  @type t :: %__MODULE__{
    :asset_id => String.t,
    :symbol => String.t,
    :exchange => String.t,
    :asset_class => BrokerAPI.Model.AssetClass.t,
    :asset_marginable => boolean() | nil,
    :avg_entry_price => String.t,
    :qty => String.t,
    :side => String.t,
    :market_value => String.t,
    :cost_basis => String.t,
    :unrealized_pl => String.t,
    :unrealized_plpc => String.t,
    :unrealized_intraday_pl => String.t,
    :unrealized_intraday_plpc => String.t,
    :current_price => String.t,
    :lastday_price => String.t,
    :change_today => String.t
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:asset_class, :struct, BrokerAPI.Model.AssetClass)
  end
end

