# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.TradeUpdateEvent do
  @moduledoc """
  Represents an update to an order/trade, sent over the events streaming api.
  """

  @derive Jason.Encoder
  defstruct [
    :account_id,
    :at,
    :event,
    :event_id,
    :execution_id,
    :order,
    :timestamp
  ]

  @type t :: %__MODULE__{
    :account_id => String.t,
    :at => DateTime.t,
    :event => BrokerAPI.Model.TradeUpdateEventType.t,
    :event_id => integer(),
    :execution_id => String.t,
    :order => BrokerAPI.Model.Order.t,
    :timestamp => DateTime.t
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:at, :datetime, nil)
     |> Deserializer.deserialize(:event, :struct, BrokerAPI.Model.TradeUpdateEventType)
     |> Deserializer.deserialize(:order, :struct, BrokerAPI.Model.Order)
     |> Deserializer.deserialize(:timestamp, :datetime, nil)
  end
end

