# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.TransferData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :transfer_type,
    :timing,
    :amount,
    :direction,
    :relationship_id,
    :additional_information,
    :bank_id
  ]

  @type t :: %__MODULE__{
    :transfer_type => String.t,
    :timing => String.t | nil,
    :amount => String.t,
    :direction => String.t,
    :relationship_id => String.t,
    :additional_information => String.t | nil,
    :bank_id => String.t
  }

  def decode(value) do
    value
  end
end

