# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.TransferType do
  @moduledoc """
  **NOTE:** The Sandbox environment currently only supports `ach`  - **ach** Transfer via ACH (US Only). - **wire** Transfer via wire (international). 
  """

  @derive Jason.Encoder
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }

  def decode(value) do
    value
  end
end

