# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.TransferResource do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :created_at,
    :updated_at,
    :type,
    :status,
    :account_id,
    :reason,
    :expires_at,
    :amount,
    :direction,
    :relationship_id,
    :additional_information,
    :bank_id
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :created_at => DateTime.t,
    :updated_at => DateTime.t,
    :type => String.t,
    :status => String.t,
    :account_id => String.t,
    :reason => String.t | nil,
    :expires_at => DateTime.t,
    :amount => String.t,
    :direction => String.t,
    :relationship_id => String.t,
    :additional_information => String.t | nil,
    :bank_id => String.t
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_at, :datetime, nil)
     |> Deserializer.deserialize(:updated_at, :datetime, nil)
     |> Deserializer.deserialize(:expires_at, :datetime, nil)
  end
end

