# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.TrustedContact do
  @moduledoc """
  This model input is optional. However, the client should make reasonable effort to obtain the trusted contact information. See more details in [FINRA Notice 17-11](https://www.finra.org/sites/default/files/Regulatory-Notice-17-11.pdf) 
  """

  @derive Jason.Encoder
  defstruct [
    :given_name,
    :family_name,
    :email_address,
    :phone_number,
    :street_address,
    :city,
    :state,
    :postal_code,
    :country
  ]

  @type t :: %__MODULE__{
    :given_name => String.t,
    :family_name => String.t,
    :email_address => String.t | nil,
    :phone_number => String.t | nil,
    :street_address => [String.t] | nil,
    :city => String.t | nil,
    :state => String.t | nil,
    :postal_code => String.t | nil,
    :country => String.t | nil
  }

  def decode(value) do
    value
  end
end

