# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.UntypedTransferData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :amount,
    :direction
  ]

  @type t :: %__MODULE__{
    :amount => String.t,
    :direction => String.t
  }

  def decode(value) do
    value
  end
end

