# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.UpdateOrderRequest do
  @moduledoc """
  Represents the fields that are editable in an order replace/update call.  Note: client_order_id is currently not editable on its own, one of the other fields must be changed at the same time to effectively replace the order
  """

  @derive Jason.Encoder
  defstruct [
    :qty,
    :time_in_force,
    :limit_price,
    :stop_price,
    :trail,
    :client_order_id
  ]

  @type t :: %__MODULE__{
    :qty => String.t | nil,
    :time_in_force => BrokerAPI.Model.TimeInForce.t | nil,
    :limit_price => String.t | nil,
    :stop_price => String.t | nil,
    :trail => String.t | nil,
    :client_order_id => String.t | nil
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:time_in_force, :struct, BrokerAPI.Model.TimeInForce)
  end
end

