# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule BrokerAPI.Model.Watchlist do
  @moduledoc """
  Represents a set of securities observed by a user.
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :account_id,
    :created_at,
    :updated_at,
    :name,
    :assets
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :account_id => String.t | nil,
    :created_at => DateTime.t | nil,
    :updated_at => DateTime.t | nil,
    :name => String.t,
    :assets => [BrokerAPI.Model.Asset.t] | nil
  }

  alias BrokerAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_at, :datetime, nil)
     |> Deserializer.deserialize(:updated_at, :datetime, nil)
     |> Deserializer.deserialize(:assets, :list, BrokerAPI.Model.Asset)
  end
end

